In [8]:
#---1---
list_1=["aman","222",777,400.4]
tup_1=tuple(list_1)
print(tup_1)

('aman', '222', 777, 400.4)


In [9]:
#---2---
info={'Roll no':'CB.EN.U4CSE20241','NAME':'DHEERAJ','SURNAME':'MUPPALLA','DOB':'25-11-2002'}
for key,value in info.items():
  print(key,':',value)

Roll no : CB.EN.U4CSE20241
NAME : DHEERAJ
SURNAME : MUPPALLA
DOB : 25-11-2002


In [10]:
#---3---
import numpy as np
np.random.seed(0)
arr1=np.random.randint(0,50,size=(2,5))
print(arr1)

[[44 47  0  3  3]
 [39  9 19 21 36]]


In [11]:
#---4---
VAR=np.random.uniform(0.0,1.0)
print(VAR)
print(abs(-1234))

0.2975346065444723
1234


In [12]:
#---5---
VAR=np.random.randint(20,91)
print(VAR)

32


In [13]:
#---6---
def retlist(list1):
  return list1[0:3]
list_1=[11,12,13,14,15]
newlist=retlist(list_1)
print(newlist)
np.random.shuffle(newlist)
print("After Shuffle :",newlist)
print(np.random.choice(list_1))

[11, 12, 13]
After Shuffle : [11, 12, 13]
11


In [14]:
#---8---
def check(x):
  if x>0:
    print("If case,x is positive")
  elif x<0:
    print("Elif case,x is negetive")
  else:
    print("Else case,x is zero")
check(5)
check(-5)
check(0)
x=0
print("-----------While loop-------------")
while(x<10):
  x+=1
  if x==5:
    print("Continue when x =5")
    continue
  if x==9:
    print("break when x=9")
    break
  print(x)
print("-----------For loop---------------")

for i in range(10,20):
  if i==15:
    print("Continue when i=15")
    continue
  if i==18:
    print("break when i=18")
    break
  print(i)

If case,x is positive
Elif case,x is negetive
Else case,x is zero
-----------While loop-------------
1
2
3
4
Continue when x =5
6
7
8
break when x=9
-----------For loop---------------
10
11
12
13
14
Continue when i=15
16
17
break when i=18


In [15]:
#---9---
string="The King is Dead, Long Live The King"
print(string)
print(string[0])
print(string[3:6])
print(string[3:])
print(string.split())

The King is Dead, Long Live The King
T
 Ki
 King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


In [16]:
#---10---
list_2=[1,4,5,8]
arr=np.array(list_2)
print("The first and second element of arr",arr[0],arr[1])


The first and second element of arr 1 4


In [18]:
#---11---
VAR_2=np.array([[1.,2.,3.],[4.,5.,6.]])
print("The 2D array :")
print(VAR_2)

The 2D array :
[[1. 2. 3.]
 [4. 5. 6.]]


In [19]:
#---12
print("Second Row",VAR_2[1:][:])
print("Second Col",VAR_2[:,1])
print("Length of the array :",len(VAR_2))

Second Row [[4. 5. 6.]]
Second Col [2. 5.]
Length of the array : 2


In [20]:
#---13---
list_3=[]
for i in range(10):
  list_3.append(np.random.randint(0,100))
oned=np.array(list_3)
print("1D array :",oned)
twod=oned.reshape(5,2)
print("2D array :\n",twod)
print("Transpose :\n",twod.T)

1D array : [81 37 25 77 72  9 20 80 69 79]
2D array :
 [[81 37]
 [25 77]
 [72  9]
 [20 80]
 [69 79]]
Transpose :
 [[81 25 72 20 69]
 [37 77  9 80 79]]


In [21]:
#---14---
l1=[1,2,3]
l2=[4,5,6]
l3=[7,8,9]
newarr=np.array([l1,l2,l3])
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
#---15---
arr_15=np.array([1,2,3])
for i in range(len(arr_15)):
  arr_15[i]=9
print(arr_15)

[9 9 9]


In [23]:
#---16---
arr16=np.array([2,4,5])
sum=0
for i in arr16:
  sum+=i
print(sum)

11


In [24]:
#---17---
arr17=np.array([77,74,75])
prod=1
for i in arr17:
  prod*=i
print(prod)

427350


In [25]:
#---18---
arr18=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print("Mean : ",np.mean(arr18))
print("Varaince : ",np.var(arr18))
print("Max :",np.max(arr18))
print("Min : ",np.min(arr18))
print("Argmin : ",np.argmin(arr18))
print("Median :",np.median(arr18))
print("Argmax : ",np.argmax(arr18))
print("Standard Deviation : ",np.std(arr18))

Mean :  12.461538461538462
Varaince :  367.32544378698225
Max : 56
Min :  1
Argmin :  1
Median : 2.0
Argmax :  12
Standard Deviation :  19.165736192147232


In [26]:
#---19---
arr19=np.array([1, 1, 7, 5, 5, 5, 4])
N_A=np.array(np.unique(arr))
N_A.sort()
print(N_A)

[1 4 5 8]


In [31]:
#--20---
VAR20=np.array([1,2,3])
VAR20_1=np.array([4,5,6])
print(np.dot(VAR20,VAR20_1))

32


In [32]:
#---21---

a=np.array([[2,12],[2,-5]])
val,vec=np.linalg.eig(a)
print("Eigen value :",val)
print("Eigen Vector :\n",vec)

Eigen value : [ 4.52079729 -7.52079729]
Eigen Vector :
 [[ 0.97864042 -0.78338465]
 [ 0.20557951  0.6215372 ]]


In [33]:
#---22---
a1=np.array([11,22,11,31])
a2=np.array([25,33,31,28])
corrcoef=np.corrcoef(a1,a2)
print(corrcoef)

[[1.         0.15997968]
 [0.15997968 1.        ]]
